import type { Metadata } from "next";
import "./globals.css";
import { Changa_One, Rubik_Mono_One, DM_Sans } from "next/font/google";
import { auth } from "@/auth";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/sonner";

const changaOne = Changa_One({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-heading",
});

const rubikMono = Rubik_Mono_One({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-subheading",
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-paragraph",
});

export const metadata: Metadata = {
  title: "SEA Catering",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <SessionProvider session={session}>
        <body
          className={`${changaOne.variable} ${rubikMono.variable} ${dmSans.variable} antialiased`}
        >
          {children}
          <Toaster className="text-foreground"/>
        </body>
      </SessionProvider>
    </html>
  );
}
