import type { Metadata } from "next";
import "./globals.css";
import { Changa_One, Rubik_Mono_One, DM_Sans } from "next/font/google";

const changaOne = Changa_One({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-heading",
});

const rubikMono = Rubik_Mono_One({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-subheading",
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-paragraph",
});

export const metadata: Metadata = {
  title: "SEA Catering",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${changaOne.variable} ${rubikMono.variable} ${dmSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
